"""empty message

Revision ID: 773f7c467eef
Revises: 9b8628156317
Create Date: 2023-08-07 22:50:11.806355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773f7c467eef'
down_revision = '9b8628156317'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    op.create_unique_constraint(op.f('uq_user_username'), 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_username'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    # ### end Alembic commands ###
